library(robotstxt)
library(rvest)
link = "https://www.britannica.com/event/World-War-II"
path = paths_allowed(link)
web = read_html(link)
View(web)
intro = web  %>% html_node("#ref1 .mw-100+ .topic-paragraph , .topic-paragraph:nth-child(1)") %>% html_text()
View(intro)
war = web  %>% html_node("section section .topic-paragraph") %>% html_text()
View(war)
text1 = data.frame(intro)
text2 = data.frame(war)
View(text1)
View(text2)
write.dcf(text1,"Introduction.doc")
write.dcf(text2,"Outbreak of War.doc")
